"""create packages table

Revision ID: e635fe3261c7
Revises:
Create Date: 2025-05-13 15:25:27.642235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e635fe3261c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    # ### end Alembic commands ###
